version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - my_network
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gocrud_api
    ports:
      - "5432:5432"
    networks:
      - my_network


networks:
  my_network:
    driver: bridge